[package]
name = "test-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
approx = "0.5.0"
rand = "0.8.4"
cv-core = "0.15.0"
nalgebra = "0.29.0"
itertools = "0.10.1"