[package]
name = "homography"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = {version = "0.54.0", features = ["clang-runtime"]}
nalgebra = "0.29.0"
bevy = "0.5"
bevy_egui = "0.7"
itertools = "0.10.1"


[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "test_proj"
path = "src/test_proj.rs"