[package]
name = "homography"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayfire = "3.8.0"
nalgebra = "0.29.0"
bevy = "0.5"
bevy_egui = "0.7"