[package]
name = "homography"
version = "0.1.0"
edition = "2018"

[dependencies]
arrsac = "0.9.0"
cv-core = "0.15.0"
derive_more = "0.99.16"
eyre = "0.6.5"
nalgebra = "0.29.0"
itertools = "0.10.1"
rand = "0.8.4"
rand_pcg = "0.3.1"
sample-consensus = "1.0.2"

[dev-dependencies]
approx = "0.5.0"